//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Museum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exhibit
    {
        public int IDExhibit { get; set; }
        public Nullable<int> IDExhibition { get; set; }
        public Nullable<int> IDRoom { get; set; }
        public int IDType { get; set; }
        public Nullable<int> IDCreator { get; set; }
        public Nullable<int> IDStyle { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string DateOfCreation { get; set; }
    
        public virtual Creator Creator { get; set; }
        public virtual Exhibition Exhibition { get; set; }
        public virtual Room Room { get; set; }
        public virtual Style Style { get; set; }
        public virtual Type Type { get; set; }
    }
}
